### ISSUE TITLE
Retornar promise nas rotas

### ISSUE THREAD

**Issue by pedro-victor** [giseleml/learn-todo#2]
Tem uma coisa errada no `getSingleTodo` e `updateTodo`. Você sabe o que é?

**Comment by giseleml** [comment]
Não estou retornando direto sem as chaves?

```js 
const getSingleTodo = () =>
    ...

const updateTodo = () =>
    ...
```

**Comment by pedro-victor** [comment]
Isso aí.
Vocë acabou tendo que alterar mais que o necessário.

**Comment by giseleml** [comment]
Sim kkk é que eu percebi que o erro de inserir uma ID inválida não tava sendo retornado corretamente
