### ISSUE TITLE
Implementar rota para anotar completude (ou não) de um todo

### ISSUE THREAD

**Issue by pedro-victor** [giseleml/learn-todo#3]
Como eu faço pra preencher o `completed`?

**Comment by giseleml** [comment]
Opa, faltou eu colocar o `completed` no método do PUT, vou arrumar agora, mas seria assim, por exemplo:
```json
'{"completed": true, "content": "study"}'
```
 Preciso criar uma rota só para isso, tipo `/completed/:id`? É que achei que fica estranho caso a pessoa queira mudar para `false`, também achei tudo no PUT mais prático, porém é errado fazer assim?

**Comment by pedro-victor** [comment]
Sim, é melhor fazer duas rotas:
`POST /todos/:id/done`
e
`POST /todos/:id/not-done`
