### ISSUE TITLE
Corrigir autorizações dadas aos usuários

### ISSUE THREAD

**Issue by pedro-victor** [giseleml/learn-todo#5]
Faz sentido a máscara que você usou para o `GET /todos` comparado ao `PUT /todos/:id`?

**Comment by giseleml** [comment]
Eu fiz assim para que só o admin pudesse ter acesso a todos os to-dos, então cada usuário so teria acesso ao to-do que criou porque só ele teria o ID do to-do criado, mas foi um 'remendo' mesmo. Pensando num cenário que vai ser individual e cada usuário terá acesso aos seus próprios to-dos apenas, então nem faz sentido ter as roles de `user` e `admin` né? Acredito que todos seriam 'admin'

**Comment by pedro-victor** [comment]
Talvez não mesmo.
Mas aí todos os usuários serão `user` na verdade.

Consegue seguir com isso?

**Comment by giseleml** [comment]
Sim, obrigada
