### ISSUE TITLE
Essa é uma lista global de ToDo ou individual por usuário?

### ISSUE THREAD

**Issue by pedro-victor** [giseleml/learn-todo#6]
Seu app está quase pronto pra ser chamado de lista global de ToDo.
Mas você acha que um app assim é útil? Como transformar ele em um app de lista de ToDo individual?

**Comment by giseleml** [comment]
Cada usuário ter acesso apenas a seus próprios to-dos, não ao de todos como é agora.

Preciso criar uma nova propriedade no schema como 'created_by' e armazenar o token do usuário que criou, dai comparar esse token com o qual a pessoa está usando para acessar e então buscar só os que ela criou?

**Comment by pedro-victor** [comment]
Exatamente!
